name: illusionist
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip

  - pip:
      # Base
      - setuptools
      - setuptools_scm
      - pylint
      - flake8
      - black
      - isort
      - twine
      - wheel
      - pytest
      - pytest-cov

      # Docs
      - mkdocs
      - mkdocs-material
      - mkdocs-minify-plugin
      - pygments
      - pymdown-extensions

      # Package
      - nbconvert<6,>=5.5.0
      - nbclient>=0.4.0
      - nbformat

      # Examples
      - notebook
      - jupyterlab
      - ipywidgets
      - matplotlib
